basePath: /api/v1
definitions:
  models.BadResponse:
    properties:
      error:
        type: string
    type: object
  models.CreateSubscription:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  models.GoodResponse:
    properties:
      message:
        type: string
    type: object
  models.ID:
    properties:
      id:
        type: string
    type: object
  models.ListSubscriptionsResponse:
    properties:
      subscriptions:
        items:
          $ref: '#/definitions/models.Subscription'
        type: array
    type: object
  models.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  models.SumSubscriptionsResponse:
    properties:
      sum:
        type: integer
    type: object
  models.UpdateSubscription:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
    type: object
host: localhost:4047
info:
  contact: {}
  description: REST-сервис для агрегации данных об онлайн-подписках пользователей.
  title: Сервис подписок API
  version: 1.0.0
paths:
  /create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для создания подписки
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateSubscription'
      produces:
      - application/json
      responses:
        "200":
          description: Id созданной подписки
          schema:
            $ref: '#/definitions/models.ID'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Создаёт новую подписку
      tags:
      - Подписки
  /delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID подписки
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Подписка удалена
          schema:
            $ref: '#/definitions/models.GoodResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Удаляет подписку по id
      tags:
      - Подписки
  /list/{user_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID пользователя
        example: '"user12345"'
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список подписок пользователя
          schema:
            $ref: '#/definitions/models.ListSubscriptionsResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Возвращает список подписок пользователя
      tags:
      - Подписки
  /read/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID подписки
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Подписка
          schema:
            $ref: '#/definitions/models.Subscription'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Получает подписку по id
      tags:
      - Подписки
  /sum:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID пользователя
        example: '"user12345"'
        in: query
        name: user_id
        required: true
        type: string
      - description: Дата начала периода
        example: 01-2006
        format: date
        in: query
        name: start_date
        required: true
        type: string
      - description: Дата окончания периода
        example: 01-2006
        format: date
        in: query
        name: end_date
        required: true
        type: string
      - description: Название сервиса
        example: '"YouTube"'
        in: query
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Сумма подписок пользователя
          schema:
            $ref: '#/definitions/models.SumSubscriptionsResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Возвращает сумму подписок пользователя
      tags:
      - Подписки
  /update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID подписки
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Данные для обновления подписки
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSubscription'
      produces:
      - application/json
      responses:
        "200":
          description: Подписка обновлена
          schema:
            $ref: '#/definitions/models.GoodResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/models.BadResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/models.BadResponse'
        "405":
          description: Метод не разрешён
          schema:
            $ref: '#/definitions/models.BadResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.BadResponse'
      summary: Обновляет подписку по id
      tags:
      - Подписки
swagger: "2.0"
